"""LangGraph state definition for JARVIS."""

from __future__ import annotations

from typing import Annotated
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class JarvisState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]
    user_query: str
    language: str        # "tr" | "en" | etc.
    memory_context: str
    needs_planning: bool
    use_pro_agent: bool  # Faz 5: route agent node to Gemini Pro for complex queries
    plan: str            # execution plan generated by planner_node (empty if not planning)
    response: str        # final text extracted by critic/formatter
    revise_count: int    # critic revision loop counter
    critic_verdict: str  # "accept" | "revise" | "redirect"
    critique: str        # feedback for executor
    confirmation_result: str  # "approved" | "denied" — set by confirmation_node
    transport: str       # Faz 4: "cli-text" | "voice-cli" | "voice-local" | "voice-remote"
                          # | "api" | "api-stream" | "api-upload" | "task-async" — set by
                          # JarvisAgent.chat()/chat_stream(); audit_log's provenance tag
