"""LangGraph state definition for JARVIS."""

from __future__ import annotations

from typing import Annotated
from typing_extensions import TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class JarvisState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]
    user_query: str
    language: str        # "tr" | "en" | etc.
    memory_context: str
    needs_planning: bool
    # Which model tier the agent and compose nodes ask for this turn. Decided by
    # jarvis/graph/role_router.py (Post-MVP Faz 2.5), not by the caller. The name
    # and the bool shape are pre-Faz-2.5 and kept so old checkpoints still load;
    # "pro" is historical -- with cloud_policy="off" both roles resolve to the
    # same local qwen3:8b and the flag only decides whether it thinks first.
    use_pro_agent: bool
    plan: str            # execution plan generated by planner_node (empty if not planning)
    response: str        # final text extracted by critic/formatter
    revise_count: int    # critic revision loop counter
    critic_verdict: str  # "accept" | "revise" | "redirect"
    critique: str        # feedback for executor
    confirmation_result: str  # "approved" | "denied" — set by confirmation_node
    transport: str       # Faz 4: "cli-text" | "voice-cli" | "voice-local" | "voice-remote"
                          # | "api" | "api-stream" | "api-upload" | "task-async" — set by
                          # JarvisAgent.chat()/chat_stream(); audit_log's provenance tag

    # Post-MVP Faz 2.75 (Paket C): ExecutionContext.to_dict() — whether a human
    # is present, can answer a confirmation, and is watching. Derived ONCE at
    # the entry point rather than re-sniffed from `transport` inside a node,
    # because a denylist on that string ("not monitor-*") silently counted the
    # background TaskExecutor as attended and let an unwatched calendar create
    # through. Absent ⇒ derive from `transport` (old checkpoints).
    execution_context: dict

    # Sprint 2 (Faz 2A): the turn's capability route as a plain dict
    # (ToolRoute.to_dict()) — the agent node binds only this subset's schemas.
    # Absent/empty ⇒ full pre-router toolset (background paths, old checkpoints).
    tool_route: dict

    # ── Patch 1.2 (Faz 1B): deterministic per-turn tool-execution accounting ──
    # All five are reset explicitly in the initial state of every turn (each
    # turn also gets a fresh thread_id, so nothing leaks via the checkpointer)
    # and read with .get() everywhere — old checkpoints without them resume
    # fine. seen vs completed is deliberate: `seen` is stamped the moment a
    # call reaches the policy layer (so a FAILED call's exact repeat is still
    # blocked), `completed` only after the tool actually returned a
    # non-error result (stamped by tool_result_accounting, the only node
    # that runs after real execution — the confirmation node can't know).
    tool_calls_attempted: int          # every call that hit the gate: run, failed or blocked
    tool_rounds: int                   # how many tool batches the agent produced this turn
    seen_tool_fingerprints: list[str]      # sha256(tool + canonical args) at policy time
    completed_tool_fingerprints: list[str]  # subset of seen that actually succeeded
    tool_execution_ledger: list[dict]  # {"tool", "fingerprint", "ok", "content_head"} per call

    # Agent Runtime rev.2, Faz 1: one ExecutionEnvelope (jarvis/execution/
    # envelope.py, .model_dump()'d) per tool call, built by
    # tool_result_accounting when Settings.execution_contract_mode !=
    # "off". Absent/empty under "off" (the default) -- old checkpoints
    # resume fine, same discipline as the five Patch-1.2 fields above.
    execution_envelopes: list[dict]

    # Agent Runtime rev.2, Faz 2: one signed ExecutionRequest
    # (jarvis/execution/request.py, .model_dump()'d) + its signature per
    # PENDING tool call in the latest agent round, built by
    # prepare_execution_node and consumed by confirmation_node right before
    # its final approve. Unlike execution_envelopes (accumulates the whole
    # turn's history), this is overwritten each round -- it only ever needs
    # to describe the batch confirmation_node is currently deciding on.
    # Absent when prepare_execution hasn't run (old checkpoints, direct-node
    # unit tests) -- confirmation_node's new checks no-op in that case.
    execution_requests: list[dict]

    # Agent Runtime rev.2, Faz 6 Part 2: pending tool calls that FAILED
    # jarvis.execution.args_schemas.validate_args() this round -- built by
    # prepare_execution_node (only calls with a registered ToolSpec.
    # args_schema are checked; everything else is absent from this list,
    # never a false negative), consumed by confirmation_node's own
    # invalid-args pre-gate. {"tool_call_id", "capability", "errors"} per
    # entry -- "errors" is pydantic's own ValidationError.errors() shape,
    # trimmed to loc/type/msg (see args_schemas.validate_args()'s docstring
    # for why "input" is deliberately dropped). Overwritten each round, same
    # "describes only the batch currently being decided on" shape as
    # execution_requests above.
    invalid_args_calls: list[dict]

    # Agent Runtime rev.2, Faz 6 Part 2: sticks for the rest of the TURN
    # (reset in the initial state dict every turn, like the Patch 1.2
    # fields above) -- True once an invalid-args batch has already been
    # rejected back to the agent once this turn. Makes "exactly one bounded
    # repair attempt" an explicit, deterministic fact instead of an
    # incidental side effect of max_tool_rounds_per_turn (which a rejected
    # batch also consumes, and which a config change would silently alter)
    # -- an external review of Faz 6 Part 1 caught that the plan's own
    # "normalize -> validate -> one repair -> ..." wording needed exactly
    # this, not an implicit reliance on the round budget.
    args_repair_attempted: bool
